#!/usr/bin/env lua
-- gen-data.lua — launch fake-wow with a version, then emit the addon's trimmed
-- data into artisan/data/<version>/ via the GM schema API:
--   skills.lua      — skills: per-pk rows, recipe inlined, learnedat order
--   item_prices.lua — item_prices: id -> avgbuyout for every id we touch
-- Projection trims what the client supplies at runtime (names, quality) and what
-- the addon derives at load (craft costs — see data.lua), keeping item_prices
-- the single price source. Bare table names are safe: the .toc loads exactly
-- one version's files.
--
-- Usage: lua gen-data.lua <version>   (default: era)

local version = arg[1] or "era"

-- Resolve repo paths from THIS file's location (works under any cwd).
local here = (debug.getinfo(1, "S").source:gsub("^@", ""):match("^(.*)/[^/]*$") or ".") .. "/"
local root = here .. "../.."
local fw = dofile(root .. "/fake-wow/init.lua")
fw.init(version)
local GM = fw.GM

-- The whole projection: outputs, their reagents, and teaching schematics all
-- get a price; skills get their recipes inlined.
local skills, prices = {}, {}
for _, pk in ipairs(GM:ListProfessions()) do
	skills[pk] = {}
	for _, s in ipairs(GM:ListSkills(pk)) do
		s.recipe = GM:GetRecipe(s.id)
		skills[pk][#skills[pk] + 1] = s
		prices[s.id] = GM:GetPrice(s.id)
		for _, rg in ipairs(s.recipe) do prices[rg.id] = GM:GetPrice(rg.id) end
		if s.scroll_id > 0 then prices[s.scroll_id] = GM:GetPrice(s.scroll_id) end
	end
end

local header = ("-- generated by artisan/scripts/gen-data.lua from fake-wow/data/%s.db; do not hand-edit.\n"):format(version)
local function lit(list) return "{" .. table.concat(list, ",") .. "}" end
local function litRec(list) -- {{reagent_id,count}, ...}
	local parts = {}
	for _, r in ipairs(list) do parts[#parts + 1] = "{" .. r.id .. "," .. r.count .. "}" end
	return "{" .. table.concat(parts, ",") .. "}"
end
local function final(first) return { header, first } end

-- ---- skills.lua ------------------------------------------------------------
local out = final("skills = {")
for _, pk in ipairs(GM:ListProfessions()) do
	out[#out + 1] = "  " .. pk .. " = {"
	for _, s in ipairs(skills[pk]) do
		-- {skill_id, craft_count, colors, phaseId, scroll_id, {{reagent_id,count},...}}
		out[#out + 1] = string.format("    {%d, %d, %s, %d, %d, %s},",
			s.id, s.craft_count, lit(s.colors), s.phaseId, s.scroll_id, litRec(s.recipe))
	end
	out[#out + 1] = "  },"
end
out[#out + 1] = "}"

-- ---- item_prices.lua -------------------------------------------------------
local ids = {}
for id in pairs(prices) do ids[#ids + 1] = id end
table.sort(ids)
local it = final("item_prices = {")
for _, id in ipairs(ids) do
	it[#it + 1] = string.format("  [%d] = %d,", id, prices[id])
end
it[#it + 1] = "}"

-- ---- profs.lua -------------------------------------------------------------
-- professions with rank spells -> their spell ids (see data/era/profs.lua use).
local pf = final("profs = {")
for _, profession in ipairs(GM:ListProfSpells()) do
	pf[#pf + 1] = "  " .. profession.pk .. " = " .. lit(profession.spells) .. ","
end
pf[#pf + 1] = "}"

local dir = root .. "/artisan/data/" .. version
os.execute("mkdir -p " .. dir)
local f = assert(io.open(dir .. "/skills.lua", "w"))
f:write(table.concat(out, "\n"), "\n")
f:close()
f = assert(io.open(dir .. "/item_prices.lua", "w"))
f:write(table.concat(it, "\n"), "\n")
f:close()
f = assert(io.open(dir .. "/profs.lua", "w"))
f:write(table.concat(pf, "\n"), "\n")
f:close()
local nskills = 0
for _, pk in ipairs(GM:ListProfessions()) do nskills = nskills + #skills[pk] end
local nprofs = 0
for _ in pairs(GM:ListProfSpells()) do nprofs = nprofs + 1 end
print("wrote " .. dir .. "/skills.lua (" .. nskills .. " skills)")
print("wrote " .. dir .. "/item_prices.lua (" .. #ids .. " items)")
print("wrote " .. dir .. "/profs.lua (" .. nprofs .. " professions)")
