#!/usr/bin/env lua
-- gen-data.lua — read fake-wow/data/era.db through its canonical loader (era.lua)
-- and emit the addon's trimmed data into skillMaster/data/era/:
--   skills.lua — skills (per-prof skill rows, positional arrays, recipe inlined)
--   item_prices.lua — item_prices: item id -> avgbuyout for every id the addon can touch
-- Projection trims what the client supplies at runtime (names, quality) and what
-- the addon derives at load (craft costs — see data.lua), keeping items the
-- single price source. Bare table names are safe: the .toc loads exactly one
-- version's files, so versions can't clash.

-- Resolve repo paths from THIS file's location (works under any cwd).
local here = (debug.getinfo(1, "S").source:gsub("^@", ""):match("^(.*)/[^/]*$") or ".") .. "/"
local root = here .. "../.."
local data = dofile(root .. "/fake-wow/era.lua").load(root .. "/fake-wow/data/era.db")

-- Skill rows keep their emitted order as the planner's level ordering, so sort
-- by learnedat once here; the field itself is not shipped.
local profs = {} -- insertion order (era.lua returns them sorted by prof_key)
local skills = {}
for _, s in ipairs(data.skills) do
	if not skills[s.prof] then
		skills[s.prof] = {}
		profs[#profs + 1] = s.prof
	end
	skills[s.prof][#skills[s.prof] + 1] = s
end
local recipes = {} -- prof -> skill_id -> {{reagent_id, count}, ...}
for _, r in ipairs(data.recipe) do
	recipes[r.prof] = recipes[r.prof] or {}
	local bySkill = recipes[r.prof]
	bySkill[r.skill_id] = bySkill[r.skill_id] or {}
	bySkill[r.skill_id][#bySkill[r.skill_id] + 1] = { r.reagent_id, r.count }
end

-- Item closure: every output, reagent (transitively — reagents may themselves
-- be crafts), and teaching schematic the addon can price.
local recipeOf = {}
for _, r in ipairs(data.recipe) do
	recipeOf[r.skill_id] = recipeOf[r.skill_id] or {}
	recipeOf[r.skill_id][#recipeOf[r.skill_id] + 1] = r
end
local craftId = {}
for _, s in ipairs(data.skills) do craftId[s.id] = true end

local needed = {}
local queue, head = {}, 1
for _, s in ipairs(data.skills) do
	queue[#queue + 1] = s.id
	if s.teach_id > 0 then queue[#queue + 1] = s.teach_id end
end
while head <= #queue do
	local id = queue[head]
	head = head + 1
	if not needed[id] then
		needed[id] = true
		if craftId[id] then
			for _, r in ipairs(recipeOf[id] or {}) do queue[#queue + 1] = r.reagent_id end
		end
	end
end

local header = "-- generated by skillMaster/scripts/gen-data.lua from fake-wow/data/era.db; do not hand-edit.\n"
local function lit(list) return "{" .. table.concat(list, ",") .. "}" end
local function litRec(list) -- {{reagent_id,count}, ...}
	local parts = {}
	for _, r in ipairs(list) do parts[#parts + 1] = "{" .. r[1] .. "," .. r[2] .. "}" end
	return "{" .. table.concat(parts, ",") .. "}"
end

-- ---- skills.lua ------------------------------------------------------------
local out = { header, "skills = {" }
for _, prof in ipairs(profs) do
	out[#out + 1] = "  " .. prof .. " = {"
	table.sort(skills[prof], function(a, b) return a.learnedat < b.learnedat end)
	local profRecipes = recipes[prof] or {}
	for _, s in ipairs(skills[prof]) do
		-- {skill_id, craft_count, colors, phaseId, teach_id, {{reagent_id,count},...}}
		out[#out + 1] = string.format("    {%d, %d, %s, %d, %d, %s},",
			s.id, s.craft_count, lit(s.colors), s.phaseId, s.teach_id,
			litRec(profRecipes[s.id] or {}))
	end
	out[#out + 1] = "  },"
end
out[#out + 1] = "}"

-- ---- item_prices.lua -------------------------------------------------------
local ids = {}
for id in pairs(needed) do ids[#ids + 1] = id end
table.sort(ids)
local it = { header, "item_prices = {" }
for _, id in ipairs(ids) do
	it[#it + 1] = string.format("  [%d] = %d,", id, (data.items[id] and data.items[id].avgbuyout) or 0)
end
it[#it + 1] = "}"

local dir = root .. "/skillMaster/data/era"
os.execute("mkdir -p " .. dir)
local f = assert(io.open(dir .. "/skills.lua", "w"))
f:write(table.concat(out, "\n"), "\n")
f:close()
f = assert(io.open(dir .. "/item_prices.lua", "w"))
f:write(table.concat(it, "\n"), "\n")
f:close()
print("wrote " .. dir .. "/skills.lua (" .. #data.skills .. " skills, " .. #data.recipe .. " recipe rows)")
print("wrote " .. dir .. "/item_prices.lua (" .. #ids .. " items)")