-- generated by skillMaster/scripts/gen-data.lua from fake-wow/data/era.db; do not hand-edit.

profs = {
  alch = {2259,3101,3464,11611},
  bs = {2018,3100,3538,9785},
  ench = {7411,7412,7413,13920},
  eng = {4036,4037,4038,12656},
  tailor = {3908,3909,3910,12180},
}
